#############################################################################
# Makefile for building: hangrymom
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  hangrymom.pro
# Template: app
# Command: /home/sgibault/Install/Qt/5.7/gcc_64/bin/qmake -o Makefile hangrymom.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Install/Qt/5.7/gcc_64/include -I../../Install/Qt/5.7/gcc_64/include/QtQuick -I../../Install/Qt/5.7/gcc_64/include/QtMultimedia -I../../Install/Qt/5.7/gcc_64/include/QtGui -I../../Install/Qt/5.7/gcc_64/include/QtQml -I../../Install/Qt/5.7/gcc_64/include/QtNetwork -I../../Install/Qt/5.7/gcc_64/include/QtSql -I../../Install/Qt/5.7/gcc_64/include/QtCore -I. -I../../Install/Qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/sgibault/Install/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = hangrymom1.0.0
DISTDIR = /home/sgibault/Developpements/AngryMom/.tmp/hangrymom1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/sgibault/Install/Qt/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/sgibault/Install/Qt/5.7/gcc_64/lib -lQt5Quick -L/usr/lib64 -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = android/AndroidManifest.xml \
		android/gradle/wrapper/gradle-wrapper.jar \
		android/gradlew \
		android/res/values/libs.xml \
		android/build.gradle \
		android/gradle/wrapper/gradle-wrapper.properties \
		android/gradlew.bat \
		TODO.txt \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		hangrymom.pro  main.cpp
QMAKE_TARGET  = hangrymom
DESTDIR       = 
TARGET        = hangrymom


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hangrymom.pro ../../Install/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../Install/Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		hangrymom.pro \
		qml.qrc \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Quick.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Multimedia.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Gui.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Qml.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Network.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Sql.prl \
		../../Install/Qt/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile hangrymom.pro
../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Install/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../../Install/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/qt.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/resources.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/moc.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../Install/Qt/5.7/gcc_64/mkspecs/features/lex.prf:
hangrymom.pro:
qml.qrc:
../../Install/Qt/5.7/gcc_64/lib/libQt5Quick.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Multimedia.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Gui.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Qml.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Network.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Sql.prl:
../../Install/Qt/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile hangrymom.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents angrymom_en.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../Install/Qt/5.7/gcc_64/bin/rcc \
		Game_item.qml \
		Game_failed.qml \
		Data_store.js \
		Game_item_explode.qml \
		Game_area.qml \
		Game_order.qml \
		Game_score_hit.qml \
		Game_win.qml \
		Game_start.qml \
		Game_success.qml \
		Game_credits.qml \
		main.qml \
		Game_array_explode.qml \
		Game_explode.qml \
		Translations/angrymom_en.qm \
		Images/astro_002.png \
		Images/astro_003.png \
		Images/astro_004.png \
		Images/astro_005.png \
		Images/bomb.png \
		Images/astro_006.png \
		Images/astro_007.png \
		Images/astro_008.png \
		Images/astro_009.png \
		Images/star.png \
		Images/fireball.png \
		Images/restart.png \
		Images/shutdown.png \
		Images/bg_header.png \
		Images/start_image.png \
		Images/explode.png \
		Images/fond_rotate.png \
		Images/title.png \
		Images/astro_010.png \
		Images/astro_011.png \
		Images/astro_012.png \
		Images/astro_013.png \
		Images/fireball_v.png \
		Images/astro_014.png \
		Images/astro_015.png \
		Images/coupe.png \
		Images/astro_001.png \
		Sounds/game_track.mp3 \
		Sounds/plop.wav \
		Sounds/rire.wav \
		Sounds/applause.wav \
		Sounds/rock_explode.wav
	/home/sgibault/Install/Qt/5.7/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../Install/Qt/5.7/gcc_64/include/QtGui/QGuiApplication \
		../../Install/Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../Install/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../Install/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Install/Qt/5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlengine.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qjsengine.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qjsvalue.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqml.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlprivate.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmllist.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qmetaobject.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmlerror.h \
		../../Install/Qt/5.7/gcc_64/include/QtQml/qqmldebug.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/QTranslator \
		../../Install/Qt/5.7/gcc_64/include/QtCore/qtranslator.h \
		../../Install/Qt/5.7/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/hangrymom/bin || mkdir -p $(INSTALL_ROOT)/opt/hangrymom/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/hangrymom/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/hangrymom/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/hangrymom/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/hangrymom/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

